services:
  frontend:
    build:
      context: ./FRONTEND
      dockerfile: Dockerfile
    expose:
      - 3000
    depends_on:
      - backend
  backend:
    build:
      context: ./BACKEND
      dockerfile: Dockerfile
    expose:
      - 8000
    ports:
      - 8000:8000
    depends_on:
      - redis
    volumes:
      - C:\imagenes:/app/storage/app/public/imagenes
  redis: 
    image: redis/redis-stack-server:7.2.0-v10
    volumes:
      - C:\redis:/data
    environment:
      - REDIS_ARGS=--requirepass contraseña_redis
  queue:
    build: 
      context: .\backend
      dockerfile: Dockerfile
    entrypoint: ["php", "artisan", "queue:work", "--sleep=3", "--tries=3"]
    depends_on:
      - redis
networks:
  default:
    external: true
    name: scoobydoo