networks:
  cedac:
services:
  frontend:
    build:
      context: .\FRONTEND
      dockerfile: Dockerfile
    environment:
      - URL_FRONTEND= http:://localhost:3000/*
    ports:
      - 3000:3000
    networks:
      - cedac
    depends_on:
      - backend
  backend:
    build:
      context: .\BACKEND
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    networks:
      - cedac
    depends_on:
      - redis
    volumes:
      - ~/imagenes:/app/storage/app/public/imagenes
  redis: 
    image: redis/redis-stack-server:7.2.0-v10
    volumes:
      - ~/redis:/data
    environment:
      - REDIS_ARGS=--requirepass contraseña_redis
    ports:
      - 6379:6379
    networks:
      - cedac
volumes:
  imagenesLaravel: