services:
  frontend:
    build:
      context: ./FRONTEND
      dockerfile: Dockerfile
    expose:
      - 3000
    volumes:
      - /imagenes:/app/public/imagenes
    depends_on:
      - backend
  backend:
    build:
      context: ./BACKEND
      dockerfile: Dockerfile
    expose:
      - 8000
    networks:
      - cedac
    depends_on:
      - redis
    volumes:
      - /imagenes:/app/storage/app/public/imagenes
  redis: 
    image: redis/redis-stack-server:7.2.0-v10
    volumes:
      - /redis:/data
    environment:
      - REDIS_ARGS=--requirepass contraseña_redis
networks:
  default:
    external: true
    name: scoobydoo